/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grahn;


public class difficultFace extends javax.swing.JFrame {

    
    private useDatabase ud = new useDatabase();
    private String difficulty;
    private String what = "Difficulty";
    
    public difficultFace() {
        
        
        initComponents();                                                       //Thanks to Mathew Broderick
        dispose();                                                              // Resizes and centres JFrame
        setUndecorated(true);
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
        
           
                                              
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hardBut = new javax.swing.JButton();
        normBut = new javax.swing.JButton();
        easyBut = new javax.swing.JButton();
        backBut = new javax.swing.JButton();
        lblBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hardBut.setBackground(new java.awt.Color(255, 255, 255));
        hardBut.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        hardBut.setText("HARD");
        hardBut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 51), new java.awt.Color(204, 255, 51), null, null));
        hardBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardButActionPerformed(evt);
            }
        });
        getContentPane().add(hardBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 670, 230, 120));

        normBut.setBackground(new java.awt.Color(255, 255, 255));
        normBut.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        normBut.setText("NORMAL");
        normBut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 51), new java.awt.Color(204, 255, 51), null, null));
        normBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normButActionPerformed(evt);
            }
        });
        getContentPane().add(normBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 670, 230, 120));

        easyBut.setBackground(new java.awt.Color(255, 255, 255));
        easyBut.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        easyBut.setText("EASY");
        easyBut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 51), new java.awt.Color(255, 255, 51), null, null));
        easyBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyButActionPerformed(evt);
            }
        });
        getContentPane().add(easyBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 670, 230, 120));

        backBut.setBackground(new java.awt.Color(255, 255, 255));
        backBut.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        backBut.setText("BACK");
        backBut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 51), new java.awt.Color(204, 255, 51), null, null));
        backBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButActionPerformed(evt);
            }
        });
        getContentPane().add(backBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 130, 50));

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grahn/difficulty backround1.png"))); // NOI18N
        getContentPane().add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 910));

        setSize(new java.awt.Dimension(1616, 946));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void easyButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyButActionPerformed
        difficulty = "Easy";
        displayDiff();
        this.dispose();
        
        ud.updateWhat(what,difficulty);                                         //Updates difficulty status to the database so that it can be fetched for later use when playing the game. sends across difficulty and column heading
        mainFace mFace = new mainFace();
        
        mFace.setVisible(true);
    }//GEN-LAST:event_easyButActionPerformed

    private void backButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButActionPerformed
        
        difficulty = "normal";
        this.dispose();
        
        mainFace mFace = new mainFace();
        ud.updateWhat(what,difficulty);                                         //Updates difficulty status to the database so that it can be fetched for later use when playing the game. sends across difficulty and column heading
        mFace.setVisible(true);
        
    }//GEN-LAST:event_backButActionPerformed

    private void hardButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardButActionPerformed
        difficulty = "Hard";
        displayDiff();
        this.dispose();
        
        ud.updateWhat(what,difficulty);                                         //Updates difficulty status to the database so that it can be fetched for later use when playing the game. sends across difficulty and column heading
        mainFace mFace = new mainFace();
        mFace.setVisible(true);
        
    }//GEN-LAST:event_hardButActionPerformed

    private void normButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normButActionPerformed
        difficulty = "Normal";
        displayDiff();
        this.dispose();
        
        ud.updateWhat(what,difficulty);                                         //Updates difficulty status to the database so that it can be fetched for later use when playing the game. sends across difficulty and column heading
        mainFace mFace = new mainFace();
        mFace.setVisible(true);
    }//GEN-LAST:event_normButActionPerformed

    public String getDifficulty()
    {
        return difficulty;                                                      //sends difficulty across
        
    }
    
    private void displayDiff()
    {
        System.out.println(difficulty);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(difficultFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(difficultFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(difficultFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(difficultFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new difficultFace().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBut;
    private javax.swing.JButton easyBut;
    private javax.swing.JButton hardBut;
    private javax.swing.JLabel lblBack;
    private javax.swing.JButton normBut;
    // End of variables declaration//GEN-END:variables
}
