/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grahn;


import java.io.*;
import java.io.File;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;


public class helpFace extends javax.swing.JFrame {

    
    public helpFace() throws IOException {
        
        initComponents();
        dispose();                                                              // Resizes and centres JFrame
        setUndecorated(true);                                                   // Mathew Broderick   
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
        
        String out = "\n";
        String line = "";
        
        Scanner scFile = new Scanner (new File("help.txt"));                    //extracts and displays help information. 
        
        while (scFile.hasNext())
        {
            line = scFile.nextLine();
            out = out + "  " + line + "\n";
        }
        scFile.close();
       
        txtHelp.setText(out);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scoreBut = new javax.swing.JButton();
        backBut = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHelp = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scoreBut.setBackground(new java.awt.Color(255, 255, 255));
        scoreBut.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        scoreBut.setText("HIGHSCORE");
        scoreBut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 51), new java.awt.Color(204, 255, 51), null, null));
        scoreBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreButActionPerformed(evt);
            }
        });
        getContentPane().add(scoreBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 380, 270, 150));

        backBut.setBackground(new java.awt.Color(255, 255, 255));
        backBut.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        backBut.setText("BACK");
        backBut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 51), new java.awt.Color(204, 255, 51), null, null));
        backBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButActionPerformed(evt);
            }
        });
        getContentPane().add(backBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 50));

        txtHelp.setColumns(20);
        txtHelp.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txtHelp.setRows(5);
        txtHelp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(txtHelp);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1240, 710));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grahn/help backround.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(2000, 2000));
        jLabel1.setPreferredSize(new java.awt.Dimension(1234, 1234));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 900));

        setSize(new java.awt.Dimension(1616, 939));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButActionPerformed
        this.dispose();
        mainFace mFace = new mainFace();
        mFace.setVisible(true);
    }//GEN-LAST:event_backButActionPerformed

    private void scoreButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreButActionPerformed
        this.dispose();
        pickHighScoreTable pt = new pickHighScoreTable();
        pt.setVisible(true);
    }//GEN-LAST:event_scoreButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(helpFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(helpFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(helpFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(helpFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new helpFace().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(helpFace.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton scoreBut;
    private javax.swing.JTextArea txtHelp;
    // End of variables declaration//GEN-END:variables
}
