/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grahn;

import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;


public class mainFace extends javax.swing.JFrame {

   private useDatabase ud = new useDatabase();
   private String[] args;
   private String what = "Status";
   
    public mainFace() {  
       
        initComponents();                                                        // Thanks to Mathew broderick
        dispose();                                                               // Resizes and centres JFrame
        setUndecorated(true);
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
       
       
        String stat = "";                                                       // This whole process ensures the loading face doesn't duplicate each time you go back to the main face. sends across colomn heading
        String option = "Status";
        stat = ud.fetchWhat(option);
        
        
        if (stat.equalsIgnoreCase("true"))
        {
            displayLoadingFace();
            stat = "false";
            ud.updateWhat(what,stat);
        }
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playBut = new javax.swing.JButton();
        helpBut = new javax.swing.JButton();
        difficultBut = new javax.swing.JButton();
        exitBut = new javax.swing.JButton();
        lblHead = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        playBut.setBackground(new java.awt.Color(255, 255, 255));
        playBut.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        playBut.setText("PLAY");
        playBut.setBorderPainted(false);
        playBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButActionPerformed(evt);
            }
        });
        getContentPane().add(playBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 310, 130));

        helpBut.setBackground(new java.awt.Color(255, 255, 255));
        helpBut.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        helpBut.setText("HELP");
        helpBut.setBorder(null);
        helpBut.setBorderPainted(false);
        helpBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButActionPerformed(evt);
            }
        });
        getContentPane().add(helpBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 310, 130));

        difficultBut.setBackground(new java.awt.Color(255, 255, 255));
        difficultBut.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        difficultBut.setText("DIFFICULTY");
        difficultBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                difficultButActionPerformed(evt);
            }
        });
        getContentPane().add(difficultBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 300, 310, 130));

        exitBut.setBackground(new java.awt.Color(255, 255, 255));
        exitBut.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        exitBut.setText("EXIT");
        exitBut.setOpaque(false);
        exitBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButActionPerformed(evt);
            }
        });
        getContentPane().add(exitBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 660, 220, 100));

        lblHead.setBackground(new java.awt.Color(0, 102, 102));
        lblHead.setFont(new java.awt.Font("Engravers MT", 1, 80)); // NOI18N
        lblHead.setForeground(new java.awt.Color(255, 255, 255));
        lblHead.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHead.setText("EAT IT");
        lblHead.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblHead.setOpaque(true);
        getContentPane().add(lblHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 520, 120));

        lblBack.setForeground(new java.awt.Color(0, 102, 255));
        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grahn/main backround1.png"))); // NOI18N
        lblBack.setOpaque(true);
        getContentPane().add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 910));

        setSize(new java.awt.Dimension(1616, 952));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void playButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButActionPerformed
        
        this.dispose();
        SnakeMain.main(args);                                                   //Starts game
        
    }//GEN-LAST:event_playButActionPerformed

    
    
    
    private void difficultButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_difficultButActionPerformed
        
        this.dispose();
        difficultFace dFace = new difficultFace();
        dFace.setVisible(true);
        
    }//GEN-LAST:event_difficultButActionPerformed

    
    private void displayLoadingFace()
    {
        loadingFace lFace = new loadingFace ();
        lFace.setVisible(true);
    }
    
    private void exitButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButActionPerformed
        
        int score = 0;
        String stat = "true";
        String close = "false";
        int id = 1;
        String difficulty = "normal";
        ud.deleteData();
        ud.InsertData(id, score, difficulty, stat, close);                      //Saves stats and additional information to the database before closing. sends across, id, score, difficulty, status, close
        System.exit(0);                                                         //Ends and closes Game (thanks to matthew broderick)
    }//GEN-LAST:event_exitButActionPerformed

    private void helpButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButActionPerformed
       try {
            this.dispose();
            helpFace hFace = new helpFace();
            hFace.setVisible(true);
        } catch (IOException ex) {        
            Logger.getLogger(mainFace.class.getName()).log(Level.SEVERE, null, ex); //needed for IOException error
            System.out.println("Help Button did not execute");
        }
    }//GEN-LAST:event_helpButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFace().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton difficultBut;
    private javax.swing.JButton exitBut;
    private javax.swing.JButton helpBut;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblHead;
    private javax.swing.JButton playBut;
    // End of variables declaration//GEN-END:variables
}
