/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grahn;

import java.util.Scanner;

public class NormalScoreFace extends javax.swing.JFrame {

    public NormalScoreFace() {
        initComponents();                                                       // Mathew Broderick
        dispose();                                                              // Resizes and centres JFrame
        setUndecorated(true);
        pack();
        setLocationRelativeTo(null);
        setVisible(true);

        useDatabase highscores = new useDatabase();
                        
        String data = highscores.displaytblHighScore("normal");                 //fetches normal players and their scores. sends across difficulty
        Scanner scData = new Scanner(data);

        int row = 0;
        int col = 0;

        while (scData.hasNextLine())                                            //Changes and displays data in table format
        {
            Scanner scLine = new Scanner(scData.nextLine()).useDelimiter("#");
            col = 0;

            while (scLine.hasNext()) {
                tblNormal.setValueAt(scLine.next(), row, col);
                col++;
            }

            row++;

            scLine.close();
        }
        scData.close();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBut = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNormal = new org.jdesktop.swingx.JXTable();
        lblHeading = new javax.swing.JLabel();
        homeBut = new javax.swing.JButton();
        lblBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBut.setBackground(new java.awt.Color(255, 255, 255));
        backBut.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        backBut.setText("BACK");
        backBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButActionPerformed(evt);
            }
        });
        getContentPane().add(backBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 50));

        tblNormal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Position", "Name", "Score"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblNormal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tblNormal.setRowHeight(50);
        tblNormal.setRowHeight(35);
        jScrollPane1.setViewportView(tblNormal);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 120, 610, 730));

        lblHeading.setBackground(new java.awt.Color(153, 255, 204));
        lblHeading.setFont(new java.awt.Font("Tahoma", 1, 45)); // NOI18N
        lblHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeading.setText("Normal Leaderboard");
        lblHeading.setOpaque(true);
        getContentPane().add(lblHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 20, 520, 80));

        homeBut.setBackground(new java.awt.Color(255, 255, 255));
        homeBut.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        homeBut.setText("HOME");
        homeBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButActionPerformed(evt);
            }
        });
        getContentPane().add(homeBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 140, 50));

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grahn/score backround.png"))); // NOI18N
        getContentPane().add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButActionPerformed
        this.dispose();
        pickHighScoreTable pt = new pickHighScoreTable();
        pt.setVisible(true);
    }//GEN-LAST:event_backButActionPerformed

    private void homeButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButActionPerformed
        this.dispose();
        mainFace mf = new mainFace();
        mf.setVisible(true);
    }//GEN-LAST:event_homeButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NormalScoreFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NormalScoreFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NormalScoreFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NormalScoreFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NormalScoreFace().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBut;
    private javax.swing.JButton homeBut;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblHeading;
    private org.jdesktop.swingx.JXTable tblNormal;
    // End of variables declaration//GEN-END:variables
}
