/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grahn;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;



public class pickHighScoreTable extends javax.swing.JFrame {

    
    public pickHighScoreTable() {
        initComponents();                                                       //Thanks to Mathew Broderick
        dispose();                                                              // Resizes and centres JFrame
        setUndecorated(true);
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        easytblBut = new javax.swing.JButton();
        normaltblBut = new javax.swing.JButton();
        hardtblBut = new javax.swing.JButton();
        backBut = new javax.swing.JButton();
        lblBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        easytblBut.setBackground(new java.awt.Color(255, 255, 255));
        easytblBut.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        easytblBut.setText("Easy High Score");
        easytblBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easytblButActionPerformed(evt);
            }
        });
        getContentPane().add(easytblBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 460, 120));

        normaltblBut.setBackground(new java.awt.Color(255, 255, 255));
        normaltblBut.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        normaltblBut.setText("Normal High Score");
        normaltblBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normaltblButActionPerformed(evt);
            }
        });
        getContentPane().add(normaltblBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 460, 120));

        hardtblBut.setBackground(new java.awt.Color(255, 255, 255));
        hardtblBut.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        hardtblBut.setText("Hard High Score");
        hardtblBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardtblButActionPerformed(evt);
            }
        });
        getContentPane().add(hardtblBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 670, 470, 120));

        backBut.setBackground(new java.awt.Color(255, 255, 255));
        backBut.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        backBut.setText("BACK");
        backBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButActionPerformed(evt);
            }
        });
        getContentPane().add(backBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, 50));

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grahn/pickHighScoreBackround.png"))); // NOI18N
        getContentPane().add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 910));

        setSize(new java.awt.Dimension(1616, 947));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void easytblButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easytblButActionPerformed
        this.dispose();
        EasyScoreFace ef = new EasyScoreFace();
        ef.setVisible(true);

    }//GEN-LAST:event_easytblButActionPerformed

    private void normaltblButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normaltblButActionPerformed
        this.dispose();
        NormalScoreFace sf = new NormalScoreFace();
        sf.setVisible(true);
    }//GEN-LAST:event_normaltblButActionPerformed

    private void hardtblButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardtblButActionPerformed
        this.dispose();
        hardScoreFace hf = new hardScoreFace();
        hf.setVisible(true);

    }//GEN-LAST:event_hardtblButActionPerformed

    private void backButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButActionPerformed
        try {
            this.dispose();
            helpFace hFace = new helpFace();

            hFace.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(pickHighScoreTable.class.getName()).log(Level.SEVERE, null, ex);  // needed for IOException error
            System.out.println("Back Button did not execute");
    }//GEN-LAST:event_backButActionPerformed

    }

    public static void main(String[] args) {

//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       /* try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(scoreFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(scoreFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(scoreFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(scoreFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        */

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pickHighScoreTable().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBut;
    private javax.swing.JButton easytblBut;
    private javax.swing.JButton hardtblBut;
    private javax.swing.JLabel lblBack;
    private javax.swing.JButton normaltblBut;
    // End of variables declaration//GEN-END:variables
}
