/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grahn;


public class saveScore extends javax.swing.JFrame {

    
    public saveScore() {
        initComponents();                                                       //Thanks to Mathew Broderick
        dispose();                                                              // Resizes and centres JFrame
        setUndecorated(true);
        pack();
        setLocationRelativeTo(null);
        setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yesBut = new javax.swing.JButton();
        noBut = new javax.swing.JButton();
        lblHeading = new javax.swing.JLabel();
        lblBackround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        yesBut.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        yesBut.setText("YES");
        yesBut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 51), new java.awt.Color(204, 255, 51), null, null));
        yesBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesButActionPerformed(evt);
            }
        });
        getContentPane().add(yesBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 270, 140));

        noBut.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        noBut.setText("NO");
        noBut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 51), new java.awt.Color(204, 255, 51), null, null));
        noBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noButActionPerformed(evt);
            }
        });
        getContentPane().add(noBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 410, 270, 140));

        lblHeading.setBackground(new java.awt.Color(0, 153, 153));
        lblHeading.setFont(new java.awt.Font("Engravers MT", 1, 50)); // NOI18N
        lblHeading.setForeground(new java.awt.Color(255, 255, 255));
        lblHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeading.setText("Would you like to save your score?");
        lblHeading.setOpaque(true);
        getContentPane().add(lblHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 1480, 110));

        lblBackround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grahn/saveScoreBackround.png"))); // NOI18N
        getContentPane().add(lblBackround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 910));

        setSize(new java.awt.Dimension(1616, 953));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void yesButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesButActionPerformed
        this.dispose();
        scoreInput sInput = new scoreInput();
        sInput.setVisible(true);

    }//GEN-LAST:event_yesButActionPerformed

    private void noButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noButActionPerformed
        this.dispose();
        mainFace mFace = new mainFace();
        mFace.setVisible(true);

    }//GEN-LAST:event_noButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(saveScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(saveScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(saveScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(saveScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new saveScore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBackround;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JButton noBut;
    private javax.swing.JButton yesBut;
    // End of variables declaration//GEN-END:variables
}
