/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grahn;

import java.awt.Color;

public class scoreInput extends javax.swing.JFrame {

    public scoreInput() {
       initComponents();                                                        //Thanks to Mathew Broderick
        dispose();                                                              // Resizes and centres JFrame
        setUndecorated(true);
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeading = new javax.swing.JLabel();
        txtNameInput = new javax.swing.JTextField();
        enterBut = new javax.swing.JButton();
        lblStat = new javax.swing.JLabel();
        lblBackround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeading.setBackground(new java.awt.Color(0, 153, 153));
        lblHeading.setFont(new java.awt.Font("Engravers MT", 1, 45)); // NOI18N
        lblHeading.setForeground(new java.awt.Color(255, 255, 255));
        lblHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeading.setText("Please type in your name and clicK Enter");
        lblHeading.setOpaque(true);
        getContentPane().add(lblHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 1510, 110));

        txtNameInput.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        txtNameInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNameInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameInputActionPerformed(evt);
            }
        });
        getContentPane().add(txtNameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 480, 150));

        enterBut.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        enterBut.setText("ENTER");
        enterBut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 51), new java.awt.Color(204, 255, 51), null, null));
        enterBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButActionPerformed(evt);
            }
        });
        getContentPane().add(enterBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 710, 290, 100));

        lblStat.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblStat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblStat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 1600, 90));

        lblBackround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grahn/scoreInputBackround.png"))); // NOI18N
        getContentPane().add(lblBackround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 910));

        setSize(new java.awt.Dimension(1616, 953));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameInputActionPerformed

    private void enterButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButActionPerformed
        
       String name = txtNameInput.getText();
       boolean stat = false;
       String nameOut = "";
       String text = "abc";
       
       
       int len = name.length();
       
       if(!name.equals(""))                                                     //Validates username
       {
          
            if(len <= 15)
            { 
                     if(name.matches("[a-zA-Z]*"))                              //Checks for non-alphabetic characters
                     {
                       nameOut = name;
                       lblStat.setText("CORRECT");
                       lblStat.setForeground(Color.green); 
                       
                       stat = true;
                       this.dispose();
                       mainFace mFace = new mainFace();
                       mFace.setVisible(true);
                     }
                     else
                     {
                         lblStat.setText("Invalid format (contains non aphabetical values)");
                         lblStat.setForeground(Color.red);
                         
                     }
                 
            }
            else
            {
              lblStat.setText("Invalid length (15 characters or less)");
              lblStat.setForeground(Color.red);
              
            }
          
       }
       else
       {
           lblStat.setText("Please enter your name");
           lblStat.setForeground(Color.red);
           
       }
       
          String difficulty = "";
         
          
      if (stat == true)
       {
           useDatabase ud = new useDatabase();
           
           System.out.println(difficulty);
           ud.UpdateTable(name);                                                //Updates database with relevant username
           
       }
       
      
           
        
       
    }//GEN-LAST:event_enterButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(scoreInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(scoreInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(scoreInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(scoreInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new scoreInput().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enterBut;
    private javax.swing.JLabel lblBackround;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblStat;
    private javax.swing.JTextField txtNameInput;
    // End of variables declaration//GEN-END:variables
}
